# Generated by Django 4.2.2 on 2023-06-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nomea', models.CharField(max_length=30)),
                ('sexoa', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('curso', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=60)),
                ('celular', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Aluno',
                'db_table': 'aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='disciplina',
            fields=[
                ('cod_disc', models.IntegerField(primary_key=True, serialize=False)),
                ('nomed', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'db_table': 'disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('masp', models.IntegerField(primary_key=True, serialize=False)),
                ('nomep', models.CharField(max_length=30)),
                ('dep', models.CharField(max_length=3)),
                ('sexop', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
            ],
            options={
                'verbose_name': 'Professore',
                'db_table': 'professor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='cursar',
            fields=[
                ('cod_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='secretaria.disciplina')),
            ],
            options={
                'verbose_name': 'Matriculas em Disciplina',
                'db_table': 'cursar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='orienta',
            fields=[
                ('matricula_o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='secretaria.aluno')),
            ],
            options={
                'verbose_name': 'Orientações',
                'db_table': 'orienta',
                'managed': False,
            },
        ),
    ]
