# Generated by Django 4.2.2 on 2023-06-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'managed': False, 'verbose_name': 'Professores'},
        ),
    ]
