# Generated by Django 4.2.2 on 2023-06-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_alter_professor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orienta',
            options={'managed': False, 'verbose_name': 'Orientaçõe'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'managed': False, 'verbose_name': 'Professore'},
        ),
    ]
